### ISSUE TITLE
Staring the project

### ISSUE THREAD

**Issue by SGalindo831** [caitlinsusbilla/CST438_Project1_Grp1#2]
We have the basics of our project. We want to proceed with the Pokemon API. We are going to create a sign-in/sign-up for users to interact with. Once user signs-in/signs-up they will be redirected to a new page that shows their current Pokemon team. They have the ability to add or drop any Pokemon they would want. We would also have a page where users can see all of the available Pokemon that they can add to their team. We can sort the list of Pokemon by type and have a name search function to search for specific Pokemon. Currently we do not have any code up. It is difficult to start the react-native environment to begin coding.

**Comment by aharo1110** [comment]
The react native environment is working
